import type { FastifyInstance, FastifyRequest } from "fastify";
import type { Prisma } from "@prisma/client";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { requireTenant } from "../../plugins/auth.js";

const managers = new Set(["OWNER", "ADMIN", "COMPLIANCE_MANAGER", "SECURITY_MANAGER"]);
const vendorInput = z.object({ name: z.string().trim().min(2).max(255), category: z.string().max(120).optional(), website: z.url().optional(), ownerName: z.string().max(120).optional(), risk: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]).default("LOW"), nextReviewDate: z.iso.datetime().nullable().optional(), active: z.boolean().default(true) });

export async function assuranceRoutes(app: FastifyInstance) {
  app.addHook("preHandler", requireTenant);
  app.get("/vendors", async request => prisma.vendor.findMany({ where: { organizationId: request.tenant.organizationId }, include: { assessments: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { name: "asc" } }));
  app.post("/vendors", async (request, reply) => { requireManager(request); const input = vendorInput.parse(request.body); const vendor = await prisma.$transaction(async tx => { const record = await tx.vendor.create({ data: { ...input, nextReviewDate: input.nextReviewDate ? new Date(input.nextReviewDate) : null, organizationId: request.tenant.organizationId, createdBy: request.tenant.userId, updatedBy: request.tenant.userId } }); await tx.activityEvent.create({ data: { organizationId: request.tenant.organizationId, actorUserId: request.tenant.userId, action: "vendor.created", entityType: "vendor", entityId: record.id } }); return record; }); return reply.code(201).send(vendor); });
  app.patch("/vendors/:id", async (request, reply) => { requireManager(request); const { id } = idParam(request.params); const input = vendorInput.partial().extend({ version: z.number().int().positive() }).parse(request.body); const current = await ownedVendor(id, request.tenant.organizationId); if (current.version !== input.version) return reply.code(409).send({ code: "VERSION_CONFLICT", current }); const { version: _, nextReviewDate, ...updates } = input; return prisma.vendor.update({ where: { id }, data: { ...updates, nextReviewDate: nextReviewDate ? new Date(nextReviewDate) : nextReviewDate, updatedBy: request.tenant.userId, version: { increment: 1 } } }); });
  app.post("/vendors/:id/assessments", async (request, reply) => { requireManager(request); const { id } = idParam(request.params); await ownedVendor(id, request.tenant.organizationId); const input = z.object({ score: z.number().int().min(0).max(100).optional(), summary: z.string().max(5000).optional(), responses: z.record(z.string(), z.unknown()).optional(), status: z.enum(["DRAFT", "IN_REVIEW", "COMPLETED"]).default("DRAFT") }).parse(request.body); const assessment = await prisma.vendorAssessment.create({ data: { ...input, responses: input.responses as Prisma.InputJsonValue | undefined, vendorId: id, assessedBy: request.tenant.userId, completedAt: input.status === "COMPLETED" ? new Date() : null } }); return reply.code(201).send(assessment); });

  app.get("/audits", async request => { const query = z.object({ frameworkId: z.string().optional() }).parse(request.query); return prisma.audit.findMany({ where: { organizationId: request.tenant.organizationId, frameworkId: query.frameworkId }, include: { findings: true }, orderBy: { createdAt: "desc" } }); });
  app.post("/audits/readiness/sync", async request => { const input = z.object({ frameworkId: z.string(), findings: z.array(z.object({ externalId: z.string().min(1).max(200), name: z.string().min(1).max(255), description: z.string().max(5000).optional(), category: z.string().max(100).optional(), domain: z.string().max(120).optional(), relatedItemId: z.string().max(200).optional(), severity: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]), ownerName: z.string().max(120).optional(), dueDate: z.iso.datetime().nullable().optional() })).max(2000) }).parse(request.body); await assertActive(request.tenant.organizationId, input.frameworkId); let audit = await prisma.audit.findFirst({ where: { organizationId: request.tenant.organizationId, frameworkId: input.frameworkId, auditType: "Automated Readiness", status: { in: ["PLANNED", "IN_PROGRESS"] } } }); if (!audit) audit = await prisma.audit.create({ data: { organizationId: request.tenant.organizationId, frameworkId: input.frameworkId, name: "Automated Readiness Audit", auditType: "Automated Readiness", status: "IN_PROGRESS", createdBy: request.tenant.userId, updatedBy: request.tenant.userId } }); await prisma.$transaction(input.findings.map(finding => prisma.auditFinding.upsert({ where: { auditId_externalId: { auditId: audit.id, externalId: finding.externalId } }, create: { ...finding, dueDate: finding.dueDate ? new Date(finding.dueDate) : null, auditId: audit.id }, update: { name: finding.name, description: finding.description, category: finding.category, domain: finding.domain, relatedItemId: finding.relatedItemId, severity: finding.severity, ownerName: finding.ownerName, dueDate: finding.dueDate ? new Date(finding.dueDate) : null } }))); return prisma.audit.findUnique({ where: { id: audit.id }, include: { findings: true } }); });
  app.post("/audits", async (request, reply) => { requireManager(request); const input = z.object({ frameworkId: z.string(), name: z.string().min(2).max(255), auditType: z.string().max(120).optional(), auditorName: z.string().max(120).optional(), startDate: z.iso.datetime().nullable().optional(), targetDate: z.iso.datetime().nullable().optional() }).parse(request.body); await assertActive(request.tenant.organizationId, input.frameworkId); const audit = await prisma.audit.create({ data: { ...input, startDate: input.startDate ? new Date(input.startDate) : null, targetDate: input.targetDate ? new Date(input.targetDate) : null, organizationId: request.tenant.organizationId, createdBy: request.tenant.userId, updatedBy: request.tenant.userId } }); return reply.code(201).send(audit); });
  app.patch("/audits/:id", async (request, reply) => { requireManager(request); const { id } = idParam(request.params); const input = z.object({ status: z.enum(["PLANNED", "IN_PROGRESS", "COMPLETED", "CANCELLED"]), version: z.number().int().positive() }).parse(request.body); const current = await ownedAudit(id, request.tenant.organizationId); if (current.version !== input.version) return reply.code(409).send({ code: "VERSION_CONFLICT", current }); return prisma.audit.update({ where: { id }, data: { status: input.status, completedAt: input.status === "COMPLETED" ? new Date() : null, updatedBy: request.tenant.userId, version: { increment: 1 } } }); });
  app.post("/audits/:id/findings", async (request, reply) => { requireManager(request); const { id } = idParam(request.params); await ownedAudit(id, request.tenant.organizationId); const input = z.object({ externalId: z.string().max(150).optional(), name: z.string().min(2).max(255), description: z.string().max(5000).optional(), category: z.string().max(100).optional(), domain: z.string().max(120).optional(), relatedItemId: z.string().max(150).optional(), severity: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]).default("MEDIUM"), ownerName: z.string().max(120).optional(), dueDate: z.iso.datetime().nullable().optional() }).parse(request.body); const finding = await prisma.auditFinding.create({ data: { ...input, dueDate: input.dueDate ? new Date(input.dueDate) : null, auditId: id } }); return reply.code(201).send(finding); });
  app.post("/audit-findings/:id/review", async request => { const { id } = idParam(request.params); const { comments } = z.object({ comments: z.string().max(5000).default("") }).parse(request.body ?? {}); const finding = await ownedFinding(id, request.tenant.organizationId); return prisma.$transaction(async tx => { const updated = await tx.auditFinding.update({ where: { id }, data: { status: "REVIEWED", reviewerName: request.user.email, reviewerId: request.tenant.userId, reviewComments: comments, reviewedAt: new Date(), version: { increment: 1 } } }); await tx.activityEvent.create({ data: { organizationId: request.tenant.organizationId, actorUserId: request.tenant.userId, action: "audit_finding.reviewed", entityType: "audit_finding", entityId: id } }); return updated; }); });
  app.post("/audit-findings/:id/resolve", async request => { requireManager(request); const { id } = idParam(request.params); await ownedFinding(id, request.tenant.organizationId); return prisma.$transaction(async tx => { const updated = await tx.auditFinding.update({ where: { id }, data: { status: "RESOLVED", resolvedAt: new Date(), resolvedBy: request.tenant.userId, version: { increment: 1 } } }); await tx.activityEvent.create({ data: { organizationId: request.tenant.organizationId, actorUserId: request.tenant.userId, action: "audit_finding.resolved", entityType: "audit_finding", entityId: id } }); return updated; }); });
}

function requireManager(request: FastifyRequest) { if (!managers.has(request.tenant.role)) throw Object.assign(new Error("Your role cannot manage assurance workflows"), { statusCode: 403 }); }
function idParam(value: unknown) { return z.object({ id: z.uuid() }).parse(value); }
function missing(entity: string) { return Object.assign(new Error(`${entity} not found`), { statusCode: 404 }); }
async function ownedVendor(id: string, organizationId: string) { const row = await prisma.vendor.findFirst({ where: { id, organizationId } }); if (!row) throw missing("Vendor"); return row; }
async function ownedAudit(id: string, organizationId: string) { const row = await prisma.audit.findFirst({ where: { id, organizationId } }); if (!row) throw missing("Audit"); return row; }
async function ownedFinding(id: string, organizationId: string) { const row = await prisma.auditFinding.findFirst({ where: { id, audit: { organizationId } } }); if (!row) throw missing("Audit finding"); return row; }
async function assertActive(organizationId: string, frameworkId: string) { const row = await prisma.organizationFramework.findUnique({ where: { organizationId_frameworkId: { organizationId, frameworkId } } }); if (!row?.active) throw Object.assign(new Error("Framework is not active"), { statusCode: 403 }); }
